server:
  port: 8222
spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: false
          routes:
            - id: product-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
            - id: customer-route
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
            - id: order-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: payment-route
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
