spring:
  datasource:
    url: jdbc:postgresql://172.24.190.23:5432/order
    username: lalith
    password: 2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.laltih.ecommerce.kafka.OrderConfirmation
server:
  port: 9020
application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    payment-url: http://localhost:9030/api/v1/payments
    product-url: http://localhost:9010/api/v1/products